### ISSUE TITLE
保存到文件？

### ISSUE THREAD

**Issue by jp1017** [Muyangmin/Android-PLog#17]
设置个开关，可以全部保存到文件

**Comment by Muyangmin** [comment]
感谢建议，保存到文件是我一直在考虑的功能，但是有一些问题还没有想清楚所以还未正式加入该功能：
**1. 是否需要保存到外部存储？**
2. 如果要保存到外部存储，如何处理权限问题？
**3. 日志文件是否需要提供文件最大限制？**
**4. 日志文件过大或过多时，应该指定怎样的清理策略？**

目前我的设想是：
- 并非所有的app都需要保存日志到文件，因此至少应该让FileLogger独立于最简单的实现。
- 不需要保存到外部存储，全部写入app的私有内部存储空间，相对安全且不需要处理文件权限问题。
- 提供文件最大值限制，一次完整的日志写入完毕后如果超出了文件大小则新建一个文件。文件名直接用序号自增的方式来处理。

> 但清理策略暂时还没有想好。

如果你对以上几个问题有想法或不同的答案，欢迎继续在这个Issue下评论，让我们一起把这个库做得更好用 :smiley:

**Comment by jp1017** [comment]
- 自定义保存目录
- 可过滤级别
- 大小可以为1M
- 文件名可用时间
