### ISSUE TITLE
为什么传入的参数不支持数字？

### ISSUE THREAD

**Issue by xuhuan** [Muyangmin/Android-PLog#18]
KLog随便什么类型传入都可以，这个目前碰到数字传入不了，能否提供个方法支持传入数字的，哪怕内部用String.valueOf一下也行。

**Comment by Muyangmin** [comment]
实际上是可以的哦，比如：

``` Java
        PLog.i("msg", 1);
        PLog.objects(2333);
        PLog.objects(3.1415926F);
```

PS: 我特意又去看了一下[KLog](https://github.com/ZhaoKaiQiang/KLog/blob/master/library/src/main/java/com/socks/library/KLog.java)的API，实际上它的方法参数签名和PLog是一样的（`Object...`）。使用Object做为参数实际上就利用了Java的`自动装箱`特性，当你传入的是一个基本类型时，可以自动识别为对应的包装类。  
当然这样的定义是有缺陷的，比如连续传入多个基本类型的参数时，我的IDE会报错。不过对于你提出的传入**一个数字**的需求应该是够用的 :smile:

**Comment by xuhuan** [comment]
@Muyangmin 我是指PLog.w/d/e这些方法，而不是objects....

**Comment by Muyangmin** [comment]
v/d/i/w/e方法目前确实需要再传入一个msg参数，但我当初设计objects的初衷就是_什么参数都可以往里扔_……
简单测试了一下，可以加入v(Object...)系列方法哈 👍

**Comment by xuhuan** [comment]
@Muyangmin 对用户来说方法越少越好吧，这样子学习成本能低点。

**Comment by Muyangmin** [comment]
如果按照这样的原则，那你的直接传入数字的需求就无法实现了。目前只能通过Objects方法来实现。

~~虽然我也一直觉得不需要太多的重载方法~~

**Comment by xuhuan** [comment]
你内部实现通过重载来实现，对于用户来说调用的时候是透明的，用户一个方法里只管扔东西进去就行了，对于用户来说，不管重载多少个方法，用户实际上只要知道1个方法就行了。

**Comment by Muyangmin** [comment]
但是如果内部解析过于复杂反而**不利于解释方法的功能和参数的作用**。

对于公开Library的主要API类来说，每一个public的方法都应当是**_意义明确、参数清晰**_的。实际上，PLog现在内部有很多私有的重载实现，但这些对于用户是透明的。

> 对于v/d/i/w/e这些方法来说，我认为msg参数相比直接传递一个基本类型的值，要重要一些。因此我不打算移除msg参数。如果真的不希望打任何日志而只是想看变量的值，这本身就是objects()方法的意义所在。 :stuck_out_tongue_winking_eye:
