### ISSUE TITLE
minsdk 14

### ISSUE THREAD

**Issue by memorise** [Muyangmin/Android-PLog#20]
如果使用minsdk=8来overrideLibrary会不会有什么影响呢？

**Comment by Muyangmin** [comment]
**理论上讲，因为library中实际调用的Android类库中的类都是从ApiLevel 1开始加入的，因此不会有影响。**如果你确实有minsdk=8的支持需求，那么使用overrideLibrary是可以的 :smile:

**Comment by memorise** [comment]
thx
