### ISSUE TITLE
请问怎么可以打印到指定文件呢？

### ISSUE THREAD

**Issue by vell001** [Muyangmin/Android-PLog#22]
请问怎么可以打印到指定文件呢？
发现有个FileLogger，但是FileNameGenerator接口是protected的，也就是只能通过context来初始化？我不能指定文件吗？

**Comment by Muyangmin** [comment]
你好，`FileLogger`确实是设计用于打印到文件的。最初我的想法是默认写入包相关的内部存储空间，因此需要使用到`Context`参数。

另外提供了一个多参数构造函数：
```Java
public FileLogger(String mLogFilePath, FileNameGenerator mFileNameGenerator,
                      long mFileSizeLimit, boolean mLogToFileOnly) {
    //...
}
```
其中第一个参数是存储路径，第二个是用于生成文件名。因为我认为不同启动时期的日志不应当是一直存在一个固定的文件中，通过这个接口可以动态生成文件名。
> 这个接口定义为protected确实不很妥当，感谢指出。


`FileLogger`目前的设计实际上是允许继承的，这样就可以使用受保护的接口了。也就是说你可以这么写：
```Java
public class MyFileLogger extends FileLogger {
    public MyFileLogger(){
        super(myPath, new TimingFileNameGenerator(),
                1024 * 1024, false);
    }
}
```
不知道能否解决你的实际需求，如果有任何问题，欢迎继续交流 😄

**Comment by vell001** [comment]
多谢啊~~~我也是用继承方式做的，暂时实现了我要的功能，很赞

不知道现在有没有文件个数控制呢？我没有发现有设置最大文件个数的接口唉，要不然日志文件会不断增长的，我现在是自己实现了一个FileNameGenerator，在nextFile函数里去删除旧日志文件，希望能有接口可以直接设置哈

**Comment by Muyangmin** [comment]
好的，本来我是有想法要做文件自动清理功能，但因为清理策略没有定好，最后没做默认实现。

> 在FileNameGenerator里做是很好的实现方式，我原先也打算这么做。

**另外，最近正在准备重构2.0版本，可以把这个功能加上去**。关于2.0版本，可以看看这里哈： #21 。如果有其他想法或想参与到维护中来，欢迎提出 😆
