### ISSUE TITLE
java.lang.OutOfMemoryError问题

### ISSUE THREAD

**Issue by vell001** [Muyangmin/Android-PLog#24]
出现了OOM了，麻烦定位下，而且给每个对外接口加个try catch，一个打日志工具导致应用本身crash有点不应该哦，现在在bugly上就这个crash次数最多了
java.lang.OutOfMemoryError
Failed to allocate a 44200098 byte allocation with 4194208 free bytes and 40MB until OOM

1 java.lang.AbstractStringBuilder.move(AbstractStringBuilder.java:388)
2 java.lang.AbstractStringBuilder.insert0(AbstractStringBuilder.java:307)
3 java.lang.StringBuilder.insert(StringBuilder.java:539)
4 java.util.Formatter.padding(Formatter.java:1652)
5 java.util.Formatter.transformFromPercent(Formatter.java:1609)
6 java.util.Formatter.transform(Formatter.java:1468)
7 java.util.Formatter.doFormat(Formatter.java:1081)
8 java.util.Formatter.format(Formatter.java:1042)
9 java.util.Formatter.format(Formatter.java:1011)
10 java.lang.String.format(String.java:1803)
11 java.lang.String.format(String.java:1777)
12 org.mym.plog.formatter.StringFormatter.format(StringFormatter.java:40)
13 org.mym.plog.PLog.log(PLog.java:339)
14 org.mym.plog.PLog.basicLog(PLog.java:171)
15 org.mym.plog.PLog.i(PLog.java:151)

**Comment by Muyangmin** [comment]
**感谢建议，2.x版本中会加入统一的try-catch。**

关于你现在的问题，可否提供一些额外的详细信息？比如使用的版本和具体打日志的那一行代码（如果不方便的话可以私信联系我）。

**Comment by vell001** [comment]
1.7.0版本，出现的原因应该是string过长，format时OOM了，我也不确定打印了什么日志内容，因为打印的是一串动态字符，可能会非常大

**Comment by Muyangmin** [comment]
OK，我会在近期的2.0正式版本上加入try-catch。
另外我会试着跑一下数据，看看能否遇到你描述的情形。
