### ISSUE TITLE
[Sample Code Misunderstand] Cannot print message when using a specific tag

### ISSUE THREAD

**Issue by johnwatsondev** [Muyangmin/Android-PLog#29]
### ENV
Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### Behaviour
Hello, buddy. I just downloaded the sample repo and test the MainActivity in app module.
The buggy code is what in `logBasic()` method:
```
PLog.i("InfoTag", "This is an info log using specified tag.");
```

Here is the SNAPSHOT of Logcat:

![plog tag bug](https://user-images.githubusercontent.com/12760754/30420028-fa98e714-98fd-11e7-9fc2-21202e5e0a47.jpg)

### Last
Thanks for hard work. :)

**Comment by johnwatsondev** [comment]
Hello, guys.
I have dived into our codebase for a while. I found this is not a bug instead of a misunderstand of API.
I think we should add some overload methods for `PLog.java`.

```java
    public static void v(String tag, String formatMsg, Object... params) {
        //TODO implement a pool of logRequest
        tag(tag).level(Log.VERBOSE).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void d(String tag, String formatMsg, Object... params) {
        tag(tag).level(Log.DEBUG).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void i(String tag, String formatMsg, Object... params) {
        tag(tag).level(Log.INFO).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void w(String tag, String formatMsg, Object... params) {
        tag(tag).level(Log.WARN).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void e(String tag, String formatMsg, Object... params) {
        tag(tag).level(Log.ERROR).msg(formatMsg).params(params).stackOffset(1).print();
    }
```

The original methods should change the name of the parameter.

```java
    public static void v(String formatMsg, Object... params) {
        //TODO implement a pool of logRequest
        new LogRequest().level(Log.VERBOSE).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void d(String formatMsg, Object... params) {
        new LogRequest().level(Log.DEBUG).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void i(String formatMsg, Object... params) {
        new LogRequest().level(Log.INFO).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void w(String formatMsg, Object... params) {
        new LogRequest().level(Log.WARN).msg(formatMsg).params(params).stackOffset(1).print();
    }

    public static void e(String formatMsg, Object... params) {
        new LogRequest().level(Log.ERROR).msg(formatMsg).params(params).stackOffset(1).print();
    }
```

This second parameter of this method was intended to be a formatted String for logging.

Here is the segment of the `format` method of `DefaultFormatter`.

![plog source code](https://user-images.githubusercontent.com/12760754/30423622-0c8361ec-9909-11e7-8ff1-7fc684d6f054.jpg)

We treated the `msg` as a formatted string.

@Muyangmin Do you have any idea about this? :) Thanks in advance.

**Comment by johnwatsondev** [comment]
@Muyangmin Do you have any idea about this? :)

**Comment by Muyangmin** [comment]
First thanks for your  carefully reviewing sample, and figure out this issue.  

After debug I found that is just a **sample code bug**. *This method called a method with compatible Java method signature (tag, msg, obj...), but that series method already removed on version 2.0.*

Sorry for bringing inconvenience for you, I will fix this right now. The library should work as expected.

**Comment by Muyangmin** [comment]
@johnwatsondev Yes your conclusion is totally right, actually there are similar signatures in 1.x: [public static void i(String tag, String msg, Object... params)](https://github.com/JumeiRdGroup/Android-PLog/blob/ea69f74323158a672f6a9cc27ee6f757bbb9a100/plog/src/main/java/org/mym/plog/PLog.java#L150).

In practice too much overload methods lead to confusion and maintaining problems, so they are replaced by builder style API.

**Comment by johnwatsondev** [comment]
We should give the user a clean Javadoc for API's usage. :) 
Thanks for the reply soon.
