### ISSUE TITLE
Allow appending log to existing file in FilePrinter

### ISSUE THREAD

**Issue by perqin** [Muyangmin/Android-PLog#31]
## Basic info
PLog version:  2.0.0

## Feature Request
So far, PLog FilePrinter overwrites the log file even if it already exists. I am wondering what is the better way to allow appending log, because I have to upload these log to the server and the old log are overwritten after the app is restarted. It would be great if FilePrinter supports appending log to existing file.

**Comment by Muyangmin** [comment]
Currently the solution is [TimingFileNameGenerator](https://github.com/JumeiRdGroup/Android-PLog/blob/904b1957f9a7f9c64221673e8949d15effc97b64/plog-printer/src/main/java/org/mym/plog/printer/FilePrinter.java#L349). By default the log file will be overwritten only if your app launches in less than a minute after last launch, this is the result of naming rule `yyyyMMdd-HHmm`. 

You can overwrite `nextFile` and `nextFileIfDuplicate` to fit your needs. If you have better idea to this API, please feel free to fill it, I'm searching for a more elegant solution for long time : )

Sorry for the long time reply after you open this issue, I'm really busy in the past week :sweat_smile:

**Comment by perqin** [comment]
@Muyangmin Actually I am using the time (accurate to second) as the filename now. Sadly I have no ideas about better API design :( I am closing this issue and will reopen it if I have any progress on it.
